# Generated by Django 6.0.6 on 2026-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expectedscore_subject_fk'),
        ('content', '0005_move_subject_to_classgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='content.subject'),
        ),
    ]
