# Generated by Django 6.0.6 on 2026-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
