# Generated by Django 6.0.6 on 2026-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_math_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
