# Generated by Django 6.0.6 on 2026-08-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_target_math_score'),
        ('accounts', '0005_populating_blank_usernames'),
    ]

    operations = [
    ]
