# Generated by Django 6.0.6 on 2026-08-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_20260803_1521"),
        ("accounts", "0006_merge_20260814_1119"),
    ]

    operations = []
