# Generated by Django 6.0.6 on 2026-09-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_20260830_1113"),
        ("accounts", "0007_merge_20260902_2355"),
    ]

    operations = []
