# Generated by Django 6.0.6 on 2026-07-02 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_testattempt_source_alter_testattempt_test'),
        ('content', '0002_lesson_tag'),
        ('roadmap', '0002_studenttopicmastery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLadderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(default=dict)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ladder_session', to='assessments.testattempt')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_sessions', to='content.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'module'], name='roadmap_cha_student_3eb53d_idx')],
            },
        ),
    ]
