# Generated by Django 6.0.6 on 2026-07-08 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_move_subject_to_classgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='content.subject'),
        ),
    ]
