# Generated by Django 6.0.6 on 2026-08-10 04:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_lesson_description_en_lesson_description_kk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NextLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('todo', 'ToDo'), ('done', 'Done')], default='todo', max_length=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_lessons', to='content.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_lessons', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_lessons', to='content.subject')),
            ],
            options={
                'ordering': ['student_id', 'date'],
                'indexes': [models.Index(fields=['student', 'date'], name='content_nex_student_08a919_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'date'), name='uniq_next_lesson_per_student_subject_day')],
            },
        ),
    ]
