# Generated by Django 6.0.6 on 2026-08-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_lesson_description_en_lesson_description_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
