# Generated by Django 6.0.6 on 2026-08-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_lesson_topic"),
        ("content", "0010_nextlesson"),
    ]

    operations = []
