from django.conf import settings
from django.core.exceptions import ValidationError as DjangoValidationError
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver

import config

# (value, label) pairs for the language field, derived from the single source of
# truth in config so adding a language there updates the model too. .capitalize()
# is enough while each label is just the value with a capital first letter.
LANGUAGE_CHOICES = [(lang, lang.capitalize()) for lang in config.SUPPORTED_LANGUAGES]


class Question(models.Model):
    text = models.TextField()
    image = models.ImageField(upload_to="questions/", null=True, blank=True)
    explanation = models.TextField()
    # Structured, deterministically-computed worked solution (steps + the rolled
    # numbers). The Tutor reads this to diagnose a student's mistake; see
    # math_engine.build_solution for the shape.
    solution = models.JSONField(default=dict, blank=True)
    # SHA-256 of the problem's mathematical identity (topic + rolled numbers),
    # set by the generation Publisher (see math_engine.compute_content_hash).
    # The unique constraint is what stops a batch run from inserting the same
    # problem twice. NULL for hand-authored / seeded questions, which carry no
    # spec and so don't participate in dedup (multiple NULLs are allowed).
    content_hash = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        unique=True,
        editable=False,
    )
    difficulty = models.PositiveSmallIntegerField(default=1)
    # Language the problem is written in. Default backfills every existing row to
    # Russian on migrate — correct, since they were all generated by the old
    # Russian-only Storyteller. No db_index: a 3-value column is too low-cardinality
    # for an index to beat a scan.
    #
    # Part of content_hash, so every language version of an item is its own row.
    # The UBT engine publishes all three at once and stores the LANGUAGE-FREE hash
    # of the mathematics in Question.solution["content_hash"]; that value is what
    # joins the three rows back together as one question, while this row's
    # content_hash carries the language so the unique constraint permits all three.
    language = models.CharField(
        max_length=10,
        choices=LANGUAGE_CHOICES,
        default=config.DEFAULT_LANGUAGE,
    )
    lesson = models.ForeignKey(
        "content.Lesson",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="questions",
    )
    tags = models.ManyToManyField(
        "content.Tag",
        related_name="questions",
    )

    def __str__(self) -> str:
        return f"Q{self.pk}: {self.text[:40]}"


class ModeFigure(models.Model):
    """The diagram for one generated-question MODE, shared by every item of it.

    Keyed on (topic, mode) rather than joined to Question, because a planimetry
    diagram is a property of the *kind* of question, not of one rolled instance:
    every ``intersecting_chords`` item wants the same picture of two chords
    crossing inside a circle, with the numbers living in the question text. That
    makes this table ~231 rows at most (one per blueprint mode) instead of one
    row per published question, and it means adding a figure later touches no
    existing Question row.

    Both keys are read from ``Question.solution``, which the UBT publisher fills
    with ``topic`` and ``mode``; hand-authored questions carry neither and so
    never match. Look up through ``assessments.figures``, never directly --
    serializing a 40-question test would otherwise be 40 extra queries.

    The SVG must contain NO WORDS. Letters, numerals and mathematical marks only.
    The engine publishes the Kazakh, Russian and English versions of an item as
    three rows sharing one ``solution["content_hash"]``, and a wordless diagram is
    what lets one row here serve all three. Wording that a reader genuinely needs
    goes in ``alt``, which is per-language by nature.
    """

    topic = models.CharField(max_length=100)
    mode = models.CharField(max_length=100)
    # Inline SVG markup, not a file: it is ~2 KB of text, it survives a pg_dump
    # with the question bank, it scales to any screen, and it spares us a media
    # root full of orphans every time a mode is re-drawn. Sanitised on save --
    # the frontend inlines this into the DOM.
    svg = models.TextField()
    # {language: description} for screen readers. Missing languages fall back to
    # no alt text rather than to another language, which would be worse.
    alt = models.JSONField(default=dict, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("topic", "mode")
        ordering = ["topic", "mode"]

    def __str__(self) -> str:
        return f"{self.topic}/{self.mode}"

    def clean(self) -> None:
        super().clean()
        from apps.assessments.figures import validate_svg

        try:
            validate_svg(self.svg)
        except ValueError as error:
            raise DjangoValidationError({"svg": str(error)}) from error

    def save(self, *args, **kwargs):
        # Deliberately not left to form validation. This markup is inlined into
        # the DOM, so an unsanitised row is stored XSS; a management command or a
        # shell import must not be able to write one.
        self.clean()
        super().save(*args, **kwargs)


@receiver([post_save, post_delete], sender=ModeFigure)
def _drop_figure_cache(sender, **kwargs) -> None:
    from apps.assessments.figures import invalidate

    invalidate()


class AnswerOption(models.Model):
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="options",
    )
    text = models.CharField(max_length=500)
    is_correct = models.BooleanField(default=False)
    # For a wrong option, the slug of the misconception that produces it (see the
    # blueprint `distractors`); empty for the correct option and untagged
    # distractors. The Tutor reads this to name the student's error. Never
    # exposed to students (see assessments.serializers).
    misconception = models.CharField(max_length=100, blank=True, default="")

    def __str__(self) -> str:
        marker = "*" if self.is_correct else " "
        return f"[{marker}] {self.text[:40]}"


class Test(models.Model):
    # Not a pytest test case — silence its Test*-name collection warning.
    __test__ = False

    TYPE_CHOICES = [
        ("micro", "Micro"),
        ("mock", "Mock"),
        ("diagnostic", "Diagnostic"),
    ]

    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    title = models.CharField(max_length=200)
    lesson = models.ForeignKey(
        "content.Lesson",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="tests",
    )
    time_limit_sec = models.PositiveIntegerField(null=True, blank=True)
    questions = models.ManyToManyField(
        Question,
        through="TestQuestion",
        related_name="tests",
    )

    def __str__(self) -> str:
        return f"{self.type}: {self.title}"


class TestQuestion(models.Model):
    # Not a pytest test case — silence its Test*-name collection warning.
    __test__ = False

    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["order"]
        unique_together = ("test", "question")

    def __str__(self) -> str:
        return f"{self.test_id}/{self.question_id} @ {self.order}"


class TestAttempt(models.Model):
    # Where this attempt came from. Test-based flows leave the default; the
    # chapter ladder (07_Chapter_Ladder_Spec.md) picks questions dynamically, so
    # its attempts carry source="ladder" with a NULL test (no synthetic Test row).

    # Not a pytest test case — silence its Test*-name collection warning.
    __test__ = False

    SOURCE_CHOICES = [
        ("test", "Test"),
        ("ladder", "Chapter ladder"),
    ]

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="attempts",
    )
    # Nullable so a ladder attempt (dynamic question set) needs no predefined
    # Test. Guarded in services.finish_attempt / _trigger_roadmap_hooks.
    test = models.ForeignKey(
        Test,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="attempts",
    )
    source = models.CharField(max_length=20, choices=SOURCE_CHOICES, default="test")
    started_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(null=True, blank=True)
    score = models.FloatField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)

    class Meta:
        indexes = [models.Index(fields=["student", "is_completed"])]

    def __str__(self) -> str:
        return f"Attempt<{self.pk}> student={self.student_id} test={self.test_id}"


class AttemptAnswer(models.Model):
    attempt = models.ForeignKey(
        TestAttempt,
        on_delete=models.CASCADE,
        related_name="answers",
    )
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected_option = models.ForeignKey(
        AnswerOption,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    is_correct = models.BooleanField(default=False)

    class Meta:
        unique_together = ("attempt", "question")

    def __str__(self) -> str:
        return f"Ans<{self.pk}> attempt={self.attempt_id} q={self.question_id}"


class TutorNote(models.Model):
    """A cached Tutor 'margin note' for one wrong answer.

    The note depends only on the question and which wrong option was chosen — not
    on the individual student — so one row is shared across every student who
    picks that option. This is the durable replacement for the old process-local
    cache: it survives restarts, is shared across workers, and makes the notes
    queryable. Written/read exclusively by ``services.get_tutor_feedback``.
    """

    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="tutor_notes",
    )
    selected_option = models.ForeignKey(
        AnswerOption,
        on_delete=models.CASCADE,
        related_name="tutor_notes",
        null = True,
        blank = True,
    )
    note = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("question", "selected_option")
        constraints = [
            models.UniqueConstraint(
                fields = ["question"],
                condition = Q(selected_option__isnull=True),
                name = "unique_tutor_explanation_per_question",
            ),
        ]

    def __str__(self) -> str:
        return f"TutorNote<{self.pk}> q={self.question_id} opt={self.selected_option_id}"
