# Generated by Django 6.0.6 on 2026-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('micro', 'Micro'), ('mock', 'Mock'), ('diagnostic', 'Diagnostic')], max_length=20),
        ),
    ]
