# Generated by Django 6.0.6 on 2026-06-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_test_type'),
        ('assessments', '0004_question_content_hash'),
    ]

    operations = [
    ]
