# Generated by Django 6.0.6 on 2026-07-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_merge_0002_alter_test_type_0004_question_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='source',
            field=models.CharField(choices=[('test', 'Test'), ('ladder', 'Chapter ladder')], default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.test'),
        ),
    ]
