# Generated by Django 6.0.6 on 2026-07-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_testattempt_source_alter_testattempt_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_notes', to='assessments.question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_notes', to='assessments.answeroption')),
            ],
            options={
                'unique_together': {('question', 'selected_option')},
            },
        ),
    ]
