# Generated by Django 6.0.6 on 2026-07-03 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_tutornote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutornote',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_notes', to='assessments.answeroption'),
        ),
        migrations.AddConstraint(
            model_name='tutornote',
            constraint=models.UniqueConstraint(condition=models.Q(('selected_option__isnull', True)), fields=('question',), name='unique_tutor_explanation_per_question'),
        ),
    ]
