# Generated by Django 6.0.6 on 2026-07-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_tutornote_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('russian', 'Russian'), ('kazakh', 'Kazakh')], default='russian', max_length=10),
        ),
    ]
