# Generated by Django 6.0.6 on 2026-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_question_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('ru', 'Ru'), ('kk', 'Kk')], default='ru', max_length=10),
        ),
    ]
