# Generated by Django 6.0.6 on 2026-08-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_test_title_en_test_title_kk_test_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('kk', 'Kk'), ('ru', 'Ru')], default='kk', max_length=10),
        ),
    ]
