# Generated by Django 6.0.6 on 2026-08-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_question_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('svg', models.TextField()),
                ('alt', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic', 'mode'],
                'unique_together': {('topic', 'mode')},
            },
        ),
    ]
