# Generated by Django 6.0.6 on 2026-06-24 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0005_merge_0002_alter_test_type_0004_question_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=80)),
                ('count', models.PositiveIntegerField()),
                ('target_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial (some questions failed)'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=80)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('architect', 'Architect'), ('storyteller', 'Storyteller'), ('critic', 'Critic'), ('publisher', 'Publisher'), ('error', 'Error')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='generation.generationjob')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_steps', to='assessments.question')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['status', 'created_at'], name='generation__status_903dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['user', 'created_at'], name='generation__user_id_5ef7a1_idx'),
        ),
        migrations.AddIndex(
            model_name='generationstep',
            index=models.Index(fields=['job', 'created_at'], name='generation__job_id_f7aa8f_idx'),
        ),
    ]
