# Generated by Django 6.0.6 on 2026-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationstep',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
