# Generated by Django 6.0.6 on 2026-07-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_alter_generationstep_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='language',
            field=models.CharField(choices=[('russian', 'Russian'), ('kazakh', 'Kazakh')], default='russian', max_length=10),
        ),
    ]
