# Generated by Django 6.0.6 on 2026-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_generationjob_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='language',
            field=models.CharField(choices=[('ru', 'Ru'), ('kk', 'Kk')], default='ru', max_length=10),
        ),
    ]
