# Generated by Django 6.0.6 on 2026-08-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_alter_generationjob_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='language',
            field=models.CharField(choices=[('kk', 'Kk'), ('ru', 'Ru'), ('en', 'En')], default='kk', max_length=10),
        ),
    ]
