# Generated by Django 6.0.6 on 2026-06-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('required_subjects', models.JSONField(default=list)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='careers.university')),
            ],
            options={
                'unique_together': {('university', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GrantThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('min_score', models.PositiveIntegerField()),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='careers.specialty')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='careers_gra_year_2ccc5a_idx')],
                'unique_together': {('specialty', 'year')},
            },
        ),
    ]
