# Generated by Django 6.0.6 on 2026-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='city_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='city_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='city_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='name_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
