# Generated by Django 6.0.6 on 2026-08-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0003_canonical_admissions_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("name_kk", models.CharField(max_length=200, null=True)),
                ("name_ru", models.CharField(max_length=200, null=True)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "slug"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionProgramGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct educational route"),
                            ("related", "Related educational route"),
                        ],
                        max_length=16,
                    ),
                ),
                ("evidence_excerpt", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_group_links",
                        to="careers.profession",
                    ),
                ),
                (
                    "program_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profession_links",
                        to="careers.educationalprogramgroup",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profession_program_links",
                        to="careers.admissionsource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profession",
            name="program_groups",
            field=models.ManyToManyField(
                related_name="professions",
                through="careers.ProfessionProgramGroup",
                to="careers.educationalprogramgroup",
            ),
        ),
        migrations.CreateModel(
            name="ProgramGroupAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("legacy_specialty_code", "Legacy specialty code"),
                            ("alternative_code", "Alternative program-group code"),
                            ("alternative_name", "Alternative program-group name"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=250)),
                ("normalized_value", models.CharField(editable=False, max_length=250)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("kk", "Kazakh"), ("ru", "Russian"), ("en", "English")],
                        max_length=2,
                    ),
                ),
                ("evidence_excerpt", models.TextField()),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="careers.educationalprogramgroup",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_group_aliases",
                        to="careers.admissionsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            (
                                "national_occupation_classifier",
                                "National occupation classifier",
                            ),
                            (
                                "legacy_occupation_classifier",
                                "Legacy occupation classifier",
                            ),
                            ("alternative_name", "Alternative profession name"),
                        ],
                        max_length=40,
                    ),
                ),
                ("value", models.CharField(max_length=250)),
                ("normalized_value", models.CharField(editable=False, max_length=250)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("kk", "Kazakh"), ("ru", "Russian"), ("en", "English")],
                        max_length=2,
                    ),
                ),
                ("evidence_excerpt", models.TextField()),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identifiers",
                        to="careers.profession",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profession_identifiers",
                        to="careers.admissionsource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scheme", "normalized_value"),
                        name="unique_profession_identifier",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_from__isnull", True),
                            ("valid_to__isnull", True),
                            ("valid_to__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="profession_identifier_dates_ordered",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="professionprogramgroup",
            constraint=models.UniqueConstraint(
                fields=("profession", "program_group"),
                name="unique_profession_program_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="programgroupalias",
            constraint=models.UniqueConstraint(
                fields=("scheme", "normalized_value"), name="unique_program_group_alias"
            ),
        ),
        migrations.AddConstraint(
            model_name="programgroupalias",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="program_group_alias_dates_ordered",
            ),
        ),
    ]
